### ISSUE TITLE
Make volume deletion idempotent

### ISSUE THREAD

**Issue by anmayes** [NimbleStorage/ansinimble#46]
Volume delete should check to see if a volume is online and exists before attempting to remove it.  Currently, if a volume isn't online the play fails with the following:

TASK [NimbleStorage.Ansinimble : Offline nimble_volume] *************************************************************************************************
FAILED - RETRYING: Offline nimble_volume (6 retries left).
FAILED - RETRYING: Offline nimble_volume (5 retries left).
FAILED - RETRYING: Offline nimble_volume (4 retries left).
FAILED - RETRYING: Offline nimble_volume (3 retries left).
FAILED - RETRYING: Offline nimble_volume (2 retries left).
FAILED - RETRYING: Offline nimble_volume (1 retries left).
fatal: [Nimble0000]: FAILED! => {"attempts": 6, "changed": false, "connection": "Close", "content": "{\"messages\":[{\"code\":\"SM_http_not_found\",\"severity\":\"error\",\"text\":\"Server has not found the requested object.\"},{\"code\":\"SM_no_method_for_URL_pattern\",\"severity\":\"error\",\"arguments\":{\"method\":\"PUT\"},\"text\":\"URL pattern in the request does not support HTTP method PUT.\"}]}", "content_type": "application/json;charset=utf-8", "date": "Tue, 28 May 2019 15:47:05 GMT", "failed": true, "json": {"messages": [{"code": "SM_http_not_found", "severity": "error", "text": "Server has not found the requested object."}, {"arguments": {"method": "PUT"}, "code": "SM_no_method_for_URL_pattern", "severity": "error", "text": "URL pattern in the request does not support HTTP method PUT."}]}, "msg": "Status code was not [200]: HTTP Error 404: OK", "redirected": false, "status": 404, "transfer_encoding": "chunked", "url": "https://172.18.144.133:5392/v1/volumes/?force=true"}

PLAY RECAP **********************************************************************************************************************************************
Nimble0000                 : ok=11   changed=0    unreachable=0    failed=1

**Comment by drajen** [comment]
Thanks for reporting this. Will fix in the next update.

**Comment by drajen** [comment]
Fixed in #49
