### ISSUE TITLE
Ansible module

### ISSUE THREAD

**Issue by jtyr** [NimbleStorage/ansinimble#54]
Is there any reason why this is not an Ansible module (or set of modules)? It's much simpler to write such thing in Python than in Ansible. And it's much more user-friendly to use module than role.

**Comment by drajen** [comment]
Hi @jtyr, Ansinimble is an unofficial Ansible role for Nimble that grew out of a TME lab. We are actively resourcing to fund an officially supported Ansible module. I have no timelines to share at this time.

**Comment by datamattsson** [comment]
Officially supported content collection released.

- https://github.com/hpe-storage/nimble-ansible-modules
